server:
  port: 8080
  
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
      
resilience4j.circuitbreaker:
  instances:
    realizaCompraCircuitBreaker:
      registerHealthIndicator: true
      ringBufferSizeInClosedState: 1 # after 7 hits circuit will be opened
      ringBufferSizeInHalfOpenState: 1
      waitDurationInOpenState: 1s # 30 seconds is the lockin period once the circuit is open
      failureRateThreshold: 100